application:
    api:
        swagger:
            path: /api-docs/swagger
            version: 3.19.4
            layout: StandaloneLayout
            deepLinking: true
            urls:
                - name: document-unpack
                  url: /api-docs/swagger/document-unpack-0.1.yml
        swagger-ui:
            path: /api-docs/swagger-ui
            urls:
                - name: document-unpack
                  url: /api-docs/swagger-ui/**

micronaut:
    application:
        name: document-unpack
    server:
        maxRequestSize: 100MB
        multipart:
            maxFileSize: 100MB
    security:
        enabled: true
        intercept-url-map:
            -
                pattern: /api-docs/swagger/document-unpack-0.1.yml
                http-method: GET
                access:
                    - isAnonymous()
        endpoints:
            login:
                enabled: true
            oauth:
                enabled: true
        token:
            jwt:
                enabled: true
                signatures:
                    secret:
                        generator:
                            secret: pleaseChangeThisSecretForANewOne
                            jws-algorithm: HS256
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: ${application.api.swagger.path}/**
            swagger-ui:
                paths: classpath:META-INF/swagger-ui
                mapping: ${application.api.swagger-ui.path}/**

consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

credentials:
    users:
        dev: dev123
        user: user123
    roles:
        dev: ADMIN
        user: VIEW