micronaut:
    application:
        name: invoice-unpack
    server:
        maxRequestSize: 100MB
        multipart:
            maxFileSize: 100MB
    security:
        enabled: true
        endpoints:
            login:
                enabled: true
            oauth:
                enabled: true
        token:
            jwt:
                enabled: true
                signatures:
                    secret:
                        generator:
                            secret: pleaseChangeThisSecretForANewOne
consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"