application:
    api:
        swagger:
            path: /api-docs/swagger
            version: 3.19.4
            layout: StandaloneLayout
            deepLinking: true
            urls:
                - name: micronaut-realworld-example-app
                  url: /api-docs/swagger/document-unpack-0.1.yml

micronaut:
    application:
        name: invoice-unpack
    server:
        maxRequestSize: 100MB
        multipart:
            maxFileSize: 100MB
#    security:
#        enabled: true
#        endpoints:
#            login:
#                enabled: true
#            oauth:
#                enabled: true
#        token:
#            jwt:
#                enabled: true
#                signatures:
#                    secret:
#                        generator:
#                            secret: pleaseChangeThisSecretForANewOne
#                            jws-algorithm: HS256
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**

consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

credentials:
    users:
        dev: dev123
        user: user123
    roles:
        dev: ADMIN
        user: VIEW