micronaut:
    application:
        name: invoice-unpack
    server:
        maxRequestSize: 100MB
        multipart:
            maxFileSize: 100MB
consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

server:
    Server 1:
        flow: both
        environment: test
        alias: "NFe-Teste"
    Server 2:
        flow: both
        environment: production
        alias: "NFe-Prod"
